name: VPS with RDP
on:
  workflow_dispatch:

jobs:
  rdp-vps:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # يبقى شغال 6 ساعات
    steps:
      - name: Install & Configure Desktop + RDP
        run: |
          sudo apt update -y
          sudo apt install -y xfce4 xfce4-goodies xrdp
          sudo systemctl enable xrdp
          sudo systemctl start xrdp
          echo "runner:admin@123" | sudo chpasswd
          echo "✅ RDP user: runner | pass: admin@123"

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=rdp-${{ github.run_id }}
          tsIP=$(tailscale ip -4 | head -n 1)
          echo "TAILSCALE_IP=$tsIP" >> $GITHUB_ENV
          echo "✅ Tailscale IP: $tsIP"

      - name: Verify RDP Access
        run: |
          echo "Tailscale VPS with RDP ready!"
          echo "IP: $env:TAILSCALE_IP"
          echo "User: runner"
          echo "Pass: admin@123"

      - name: Keep VPS Alive
        run: |
          while true; do
            echo "[$(date)] VPS running..."
            sleep 300
          done
